/**
 * SchemaComparison.tsx
 * Compare schemas between two database connections.
 * Onobase — Obnet Pty Ltd © 2026
 */

import { useState, useCallback } from 'react'
import { AgGridReact } from 'ag-grid-react'
import type { ColDef } from 'ag-grid-community'

// ── Types ─────────────────────────────────────────────────────────────────────

interface ColumnDiff {
  table: string
  column: string
  status: 'added' | 'removed' | 'changed'
  detail: string
}

interface CompareResult {
  onlyInA: string[]
  onlyInB: string[]
  inBoth: string[]
  columnDiffs: ColumnDiff[]
  summary: { tablesOnlyInA: number; tablesOnlyInB: number; tablesInBoth: number; columnDiffs: number }
}

interface Props {
  connectionA: { dbName: string; host: string } | null
  onOpenScript?: (sql: string, title: string) => void
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const CONN_COLORS = [
  '#00E5B0', '#3B82F6', '#8B5CF6', '#F97316',
  '#EF4444', '#EAB308', '#EC4899', '#06B6D4',
]

type DbType = 'postgresql' | 'mysql' | 'mssql' | 'sqlite'
function defaultPort(t: DbType) { return t === 'mysql' ? 3306 : t === 'mssql' ? 1433 : t === 'sqlite' ? 0 : 5432 }

// ── Component ─────────────────────────────────────────────────────────────────

export default function SchemaComparison({ connectionA, onOpenScript }: Props) {
  const [bHost, setBHost]       = useState('localhost')
  const [bPort, setBPort]       = useState(5432)
  const [bUser, setBUser]       = useState('postgres')
  const [bPass, setBPass]       = useState('')
  const [bDb, setBDb]           = useState('')
  const [bType, setBType]       = useState<DbType>('postgresql')
  const [bColor, setBColor]     = useState('#3B82F6')
  const [bConnected, setBConnected] = useState(false)
  const [bName, setBName]       = useState('')
  const [connecting, setConnecting] = useState(false)
  const [comparing, setComparing]   = useState(false)
  const [error, setError]           = useState<string | null>(null)
  const [result, setResult]         = useState<CompareResult | null>(null)
  const [activeTab, setActiveTab]   = useState<'onlyA' | 'onlyB' | 'diffs'>('onlyA')

  const connectB = useCallback(async () => {
    setConnecting(true); setError(null)
    const res = await window.electronAPI.connectCompare({
      host: bHost, port: bPort, database: bDb,
      user: bUser, password: bPass, dbType: bType,
    })
    setConnecting(false)
    if (res.ok) { setBConnected(true); setBName(bDb) }
    else setError(res.error)
  }, [bHost, bPort, bDb, bUser, bPass, bType])

  const compare = useCallback(async () => {
    setComparing(true); setError(null)
    const res = await window.electronAPI.compareSchemas()
    setComparing(false)
    if (res.ok) setResult(res)
    else setError(res.error)
  }, [])

  const generateMigration = useCallback(() => {
    if (!result) return
    const lines: string[] = ['-- Migration: Make A match B', '-- Generated by Onobase Schema Comparison', '']

    for (const t of result.onlyInB) {
      lines.push(`-- Table missing in A — create it:`)
      lines.push(`-- CREATE TABLE ${t} ( ... );`)
      lines.push('')
    }
    for (const t of result.onlyInA) {
      lines.push(`DROP TABLE IF EXISTS ${t}; -- Only in A, not in B`)
    }
    for (const diff of result.columnDiffs) {
      const [schema, table] = diff.table.split('.')
      if (diff.status === 'added') {
        lines.push(`ALTER TABLE "${schema}"."${table}" ADD COLUMN "${diff.column}" TEXT; -- ${diff.detail}`)
      } else if (diff.status === 'removed') {
        lines.push(`ALTER TABLE "${schema}"."${table}" DROP COLUMN "${diff.column}"; -- ${diff.detail}`)
      } else {
        lines.push(`-- ALTER TABLE "${schema}"."${table}" ALTER COLUMN "${diff.column}" TYPE ...; -- ${diff.detail}`)
      }
    }

    onOpenScript?.(lines.join('\n'), 'Migration Script')
  }, [result, onOpenScript])

  const colDefs: ColDef[] = [
    { field: 'table', headerName: 'Table', flex: 1, minWidth: 180 },
    { field: 'column', headerName: 'Column', flex: 1, minWidth: 120 },
    {
      field: 'status', headerName: 'Status', width: 100,
      cellStyle: (p: { value: string }) => ({
        color: p.value === 'added' ? '#00E5B0' : p.value === 'removed' ? '#EF4444' : '#EAB308',
        fontWeight: 600,
      }),
    },
    { field: 'detail', headerName: 'Detail', flex: 2 },
  ]

  const inp: React.CSSProperties = {
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: 5, padding: '6px 8px', fontSize: 12,
    color: '#C9D1D9', fontFamily: 'var(--font-mono)', outline: 'none',
  }
  const btn = (primary = false): React.CSSProperties => ({
    background: primary ? 'rgba(0,229,176,0.1)' : 'rgba(255,255,255,0.05)',
    border: `1px solid ${primary ? 'rgba(0,229,176,0.3)' : 'rgba(255,255,255,0.1)'}`,
    borderRadius: 6, color: primary ? '#00E5B0' : '#8B949E',
    padding: '6px 14px', fontSize: 12, cursor: 'pointer',
    fontFamily: 'var(--font-body)', transition: 'all 0.15s',
  })
  const tabBtn = (active: boolean): React.CSSProperties => ({
    background: 'transparent', border: 'none',
    borderBottom: `2px solid ${active ? '#00E5B0' : 'transparent'}`,
    color: active ? '#C9D1D9' : '#484F58',
    padding: '7px 14px', fontSize: 12, cursor: 'pointer',
    fontFamily: 'var(--font-body)', fontWeight: active ? 600 : 400,
    transition: 'all 0.15s',
  })

  return (
    <div style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden', background: '#0D1117', padding: 20, gap: 20 }}>

      {/* Connection panels */}
      <div style={{ display: 'flex', gap: 16, flexShrink: 0 }}>

        {/* Panel A — current connection */}
        <div style={{ flex: 1, background: '#161B22', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 8, padding: 14 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 10, fontFamily: 'var(--font-body)', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#484F58' }}>Connection A (Primary)</span>
            <span style={{ fontSize: 9, background: 'rgba(0,229,176,0.1)', border: '1px solid rgba(0,229,176,0.25)', borderRadius: 3, padding: '1px 6px', color: '#00E5B0', fontFamily: 'var(--font-mono)' }}>Primary</span>
          </div>
          {connectionA ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#00E5B0', boxShadow: '0 0 6px rgba(0,229,176,0.5)' }} />
              <span style={{ fontSize: 12, fontFamily: 'var(--font-mono)', color: '#C9D1D9' }}>{connectionA.dbName}</span>
              <span style={{ fontSize: 10, color: '#484F58', fontFamily: 'var(--font-mono)' }}>{connectionA.host}</span>
            </div>
          ) : (
            <span style={{ fontSize: 12, color: '#484F58', fontFamily: 'var(--font-body)' }}>No active connection</span>
          )}
        </div>

        {/* Panel B — compare connection */}
        <div style={{ flex: 2, background: '#161B22', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 8, padding: 14 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 10, fontFamily: 'var(--font-body)', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#484F58' }}>Connection B (Compare)</span>
            {bConnected && (
              <span style={{ fontSize: 9, background: 'rgba(59,130,246,0.1)', border: '1px solid rgba(59,130,246,0.25)', borderRadius: 3, padding: '1px 6px', color: '#3B82F6', fontFamily: 'var(--font-mono)' }}>Compare</span>
            )}
          </div>
          {bConnected ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#3B82F6', boxShadow: '0 0 6px rgba(59,130,246,0.5)' }} />
              <span style={{ fontSize: 12, fontFamily: 'var(--font-mono)', color: '#C9D1D9' }}>{bName}</span>
              <span style={{ fontSize: 10, color: '#484F58' }}>{bHost}</span>
              <button style={{ ...btn(), marginLeft: 'auto', fontSize: 11 }} onClick={() => { setBConnected(false); window.electronAPI.disconnectCompare() }}>Disconnect B</button>
            </div>
          ) : (
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'flex-end' }}>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>HOST</div>
                <input style={{ ...inp, width: 120 }} value={bHost} onChange={e => setBHost(e.target.value)} placeholder="host" />
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>PORT</div>
                <input style={{ ...inp, width: 60 }} type="number" value={bPort} onChange={e => setBPort(Number(e.target.value))} />
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>DATABASE</div>
                <input style={{ ...inp, width: 120 }} value={bDb} onChange={e => setBDb(e.target.value)} placeholder="database" />
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>USER</div>
                <input style={{ ...inp, width: 90 }} value={bUser} onChange={e => setBUser(e.target.value)} />
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>PASSWORD</div>
                <input style={{ ...inp, width: 90 }} type="password" value={bPass} onChange={e => setBPass(e.target.value)} />
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#484F58', marginBottom: 3, fontFamily: 'var(--font-body)' }}>TYPE</div>
                <select style={{ ...inp, width: 110 }} value={bType} onChange={e => { const t = e.target.value as DbType; setBType(t); setBPort(defaultPort(t)) }}>
                  {(['postgresql', 'mysql', 'mssql', 'sqlite'] as const).map(t => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              <button style={btn(true)} onClick={connectB} disabled={connecting || !bDb}>
                {connecting ? 'Connecting…' : 'Connect B'}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Compare button */}
      {connectionA && bConnected && (
        <div style={{ display: 'flex', gap: 10, flexShrink: 0 }}>
          <button style={{ ...btn(true), padding: '8px 20px' }} onClick={compare} disabled={comparing}>
            {comparing ? 'Comparing…' : '⇄ Compare Schemas'}
          </button>
          {result && (
            <button style={btn()} onClick={generateMigration}>
              📜 Generate Migration Script
            </button>
          )}
        </div>
      )}

      {/* Error */}
      {error && (
        <div style={{ padding: '8px 12px', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 6, color: '#EF4444', fontSize: 12, fontFamily: 'var(--font-mono)', flexShrink: 0 }}>
          ⚠ {error}
        </div>
      )}

      {/* Summary cards */}
      {result && (
        <div style={{ display: 'flex', gap: 12, flexShrink: 0 }}>
          {[
            { label: 'Only in A', value: result.summary.tablesOnlyInA, color: '#EF4444', bg: 'rgba(239,68,68,0.06)' },
            { label: 'Only in B', value: result.summary.tablesOnlyInB, color: '#22C55E', bg: 'rgba(34,197,94,0.06)' },
            { label: 'In Both', value: result.summary.tablesInBoth, color: '#00E5B0', bg: 'rgba(0,229,176,0.06)' },
            { label: 'Column Diffs', value: result.summary.columnDiffs, color: '#EAB308', bg: 'rgba(234,179,8,0.06)' },
          ].map(({ label, value, color, bg }) => (
            <div key={label} style={{
              background: bg, border: `1px solid ${color}25`,
              borderRadius: 8, padding: '10px 16px',
              display: 'flex', flexDirection: 'column', gap: 3, minWidth: 100,
            }}>
              <span style={{ fontSize: 22, fontWeight: 700, color, fontFamily: 'var(--font-heading)' }}>{value}</span>
              <span style={{ fontSize: 10, color: '#8B949E', fontFamily: 'var(--font-body)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{label}</span>
            </div>
          ))}
        </div>
      )}

      {/* Results tabs */}
      {result && (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', background: '#161B22', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 8 }}>
          <div style={{ display: 'flex', borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
            <button style={tabBtn(activeTab === 'onlyA')} onClick={() => setActiveTab('onlyA')}>
              Only in A ({result.onlyInA.length})
            </button>
            <button style={tabBtn(activeTab === 'onlyB')} onClick={() => setActiveTab('onlyB')}>
              Only in B ({result.onlyInB.length})
            </button>
            <button style={tabBtn(activeTab === 'diffs')} onClick={() => setActiveTab('diffs')}>
              Column Differences ({result.columnDiffs.length})
            </button>
          </div>

          <div style={{ flex: 1, overflow: 'auto' }}>
            {activeTab !== 'diffs' && (
              <div style={{ padding: 8 }}>
                {(activeTab === 'onlyA' ? result.onlyInA : result.onlyInB).map(t => (
                  <div key={t} style={{
                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    padding: '6px 12px', borderRadius: 5, marginBottom: 2,
                    background: activeTab === 'onlyA' ? 'rgba(239,68,68,0.04)' : 'rgba(34,197,94,0.04)',
                    border: `1px solid ${activeTab === 'onlyA' ? 'rgba(239,68,68,0.1)' : 'rgba(34,197,94,0.1)'}`,
                  }}>
                    <span style={{ fontSize: 12, fontFamily: 'var(--font-mono)', color: '#C9D1D9' }}>{t}</span>
                    <button
                      style={{ ...btn(), fontSize: 10, padding: '2px 8px' }}
                      onClick={async () => {
                        const [schema, table] = t.split('.')
                        const res = await window.electronAPI.scriptObject({ objectType: 'table', schemaName: schema, objectName: table, scriptType: 'create' })
                        if (res.ok) onOpenScript?.(res.sql, `Script: ${table}`)
                      }}
                    >
                      Script CREATE
                    </button>
                  </div>
                ))}
                {(activeTab === 'onlyA' ? result.onlyInA : result.onlyInB).length === 0 && (
                  <div style={{ padding: 24, textAlign: 'center', color: '#484F58', fontSize: 12, fontFamily: 'var(--font-body)' }}>No differences</div>
                )}
              </div>
            )}

            {activeTab === 'diffs' && (
              <div className="ag-theme-balham-dark" style={{ height: '100%' }}>
                <AgGridReact
                  rowData={result.columnDiffs}
                  columnDefs={colDefs}
                  defaultColDef={{ sortable: true, resizable: true, filter: false }}
                  rowHeight={26}
                  headerHeight={32}
                  domLayout="normal"
                  animateRows={false}
                />
              </div>
            )}
          </div>
        </div>
      )}

      {!result && !error && connectionA && (
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#484F58', fontSize: 13, fontFamily: 'var(--font-body)', flexDirection: 'column', gap: 8 }}>
          <span style={{ fontSize: 32 }}>⇄</span>
          <span>{bConnected ? 'Click "Compare Schemas" to begin' : 'Connect Database B to compare'}</span>
        </div>
      )}

      <style>{`.ag-theme-balham-dark{--ag-background-color:#161B22;--ag-header-background-color:#1C2330;--ag-row-hover-color:rgba(255,255,255,0.04);--ag-border-color:rgba(255,255,255,0.07);--ag-foreground-color:#C9D1D9;--ag-font-family:var(--font-mono);--ag-font-size:11px}`}</style>
    </div>
  )
}

// Colour picker mini
function ColorDot({ colors, selected, onSelect }: { colors: string[]; selected: string; onSelect: (c: string) => void }) {
  return (
    <div style={{ display: 'flex', gap: 6 }}>
      {colors.map(c => (
        <div
          key={c}
          onClick={() => onSelect(c)}
          style={{
            width: 16, height: 16, borderRadius: '50%', background: c,
            cursor: 'pointer', outline: selected === c ? `2px solid ${c}` : 'none', outlineOffset: 2,
          }}
        />
      ))}
    </div>
  )
}

// Keep ColorDot available for ConnectionManager
export { CONN_COLORS, ColorDot }
