import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  connectDB:     (config: object) => ipcRenderer.invoke('db:connect', config),
  disconnectDB:  ()               => ipcRenderer.invoke('db:disconnect'),
  listDatabases: (config: object) => ipcRenderer.invoke('db:listDatabases', config),
  queryDB:       (sql: string, params: unknown[]) => ipcRenderer.invoke('db:query', sql, params),
  getSchema:     ()               => ipcRenderer.invoke('db:schema'),
  saveFile:      (content: string, defaultPath?: string) => ipcRenderer.invoke('dialog:saveFile', content, defaultPath),
  openFile:      ()               => ipcRenderer.invoke('dialog:openFile'),
  saveLayout:    (connectionKey: string, layout: unknown) => ipcRenderer.invoke('layout:save', connectionKey, layout),
  loadLayout:    (connectionKey: string) => ipcRenderer.invoke('layout:load', connectionKey),
  getObjects:    (type: string) => ipcRenderer.invoke('db:objects', type),
  scriptObject:  (config: object) => ipcRenderer.invoke('db:scriptObject', config),
  explainQuery:  (sql: string) => ipcRenderer.invoke('db:explain', sql),
  getActivity:   () => ipcRenderer.invoke('db:activity'),
  killQuery:     (pid: number) => ipcRenderer.invoke('db:killQuery', pid),
  gitOpenRepo:   () => ipcRenderer.invoke('git:openRepo'),
  gitStatus:     (repoPath: string) => ipcRenderer.invoke('git:status', repoPath),
  gitCommit:     (config: object) => ipcRenderer.invoke('git:commit', config),
  gitLog:        (repoPath: string) => ipcRenderer.invoke('git:log', repoPath),
  updateCell:       (config: object) => ipcRenderer.invoke('db:updateCell', config),
  deleteRows:       (config: object) => ipcRenderer.invoke('db:deleteRows', config),
  insertRows:       (config: object) => ipcRenderer.invoke('db:insertRows', config),
  searchAll:        (config: object) => ipcRenderer.invoke('db:searchAll', config),
  connectCompare:   (config: object) => ipcRenderer.invoke('db:connectCompare', config),
  compareSchemas:   ()               => ipcRenderer.invoke('db:compareSchemas'),
  disconnectCompare:()               => ipcRenderer.invoke('db:disconnectCompare'),
  logAppend:        (entry: object)  => ipcRenderer.invoke('log:append', entry),
  logLoad:          (config: object) => ipcRenderer.invoke('log:load', config),
  logClear:         ()               => ipcRenderer.invoke('log:clear'),
  sshConnect:       (config: object) => ipcRenderer.invoke('ssh:connect', config),
  sshDisconnect:    ()               => ipcRenderer.invoke('ssh:disconnect'),
  getHealth:        ()               => ipcRenderer.invoke('db:health'),
})
